### ISSUE TITLE
Need to explain the sources of llbmc-bench and GNU Coreutils

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee-examples#23]
README.md should given an explanation on the sources of llbmc-bench (to give proper credit), coreutils (GNU) and how they may be different from the original.

**Comment by feliciahalim** [comment]
@domainexpert It has been updated in here : https://github.com/feliciahalim/klee-examples/pull/25

**Comment by domainexpert** [comment]
#25 Merged.
