### ISSUE TITLE
Deletion of tr_nosyscall.c

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee-examples#26]
I suggest the removal of scalability/tr_nosyscall.c as its run doesn't terminate, and now we have a terminating replacement: scalabilty/tr_nosyscall2.c, which I also suggest to be renamed to scalability/tr_nosyscall.c

**Comment by feliciahalim** [comment]
@domainexpert It has been updated, as can be seen in here: https://github.com/feliciahalim/klee-examples/blob/master/scalability/tr_nosyscall.c

**Comment by domainexpert** [comment]
@feliciahalim Awesome!
