### ISSUE TITLE
Update Makefiles to Use LLVM 3 File Extension Convention

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/klee-examples#27]
Right now, tools are assumed to be LLVM 2.9, such that bitcode file extension is assumed to be .o and assembly code is assumed to be .s. This requires renaming from LLVM 3 output. I think we should avoid the renamings in the Makefiles, and let the bitcode file be .bc and assembly code be .ll.

**Comment by feliciahalim** [comment]
PR https://github.com/tracer-x/klee-examples/pull/28 has been merged to handle this issue.
